### ISSUE TITLE
Visualisation not found on server error

### ISSUE THREAD

**Issue by ArjandenOuden** [mhamano/advanced-analytics-toolbox#1]
After successfully installing and configuring and testing R, Rserve and SSEtoRserve and the prerequisite packages for R for the advanced-analytics-toolbox i end up with this error below after pulling the extension onto the worksheet:

![image](https://user-images.githubusercontent.com/30589212/28768457-f597a53c-75d7-11e7-845f-737ebc411655.png)

What have i missed? Where can i look for errors in the Qlik Sense logfiles?

I absolutely love this extension and would VERY much like it to work as in the youtube demo video :-)

I've upgrade June 2017 to Patch1, rebooted several times, reinstalled the advanced analytics toolbox extension. This is on a AWS box, win server 2012R2.

Please help

**Comment by mhamano** [comment]
Hi, would you make sure that you are using the extension zip file named "advanced-analytics-toolbox-1.0.0.zip" downloaded from the release page (https://github.com/mhamano/advanced-analytics-toolbox/releases), not the one directly downloaded from the git repository? If you are using the right one, would you launch the developer tool by pressing [F12] on the browser and check if there are any errors on the console? I have been working on June 2017 Patch 1 of both desktop and server, and things are working fine.

**Comment by ArjandenOuden** [comment]
Hello Mr. Hamano,
This did the trick, i've used a zip called advanced-analytics-toolbox-master.zip but that was wrong. All is working now, thank you so much!!

**Comment by mhamano** [comment]
Other people might face the same issue, so I am going to make it more obvious that the zip file needs to be downloaded from the release page. Thank you for your report.
