### ISSUE TITLE
Iterating through full hypercube

### ISSUE THREAD

**Issue by balexbyrd** [mhamano/advanced-analytics-toolbox#14]
First - I love what you're doing for this community, you've really built some great work. 

I was reading through your code and noticed that you're not iterating through the full hypercube. For example, when I run kmeans  [https://github.com/mhamano/advanced-analytics-toolbox/blob/master/src/lib/js/analysis/kmeans.js](url) R is only going to run the analysis on the first 1500 rows and return a result without an error. This method presents a problem to the end user who assumes it's the full data set which could easily be over 1,500 or even 10K rows - at which point the model needs to handle multiple pages). 

While I love the concept of you continuing to build multiple models in short order, this is a very big issue that's not intuitive to a layman end-user and needs to be factored in before this is a fully built, blessed, and distributed solution.

**Comment by mhamano** [comment]
Hi Alex, thank you for your valuable suggestion. Handling multiple dataPages in scatter charts is one of the functions I left for the future enhancement, and I'll try to include it in the next release.

**Comment by mhamano** [comment]
Hi, this is fixed in v1.3.0. e896ec2d8a1f328136be8c539606e6a8b05315b7
https://github.com/mhamano/advanced-analytics-toolbox/releases/edit/v1.3.0#
