### ISSUE TITLE
Color-picker not working in September 2017

### ISSUE THREAD

**Issue by DavidStorek** [mhamano/advanced-analytics-toolbox#40]
Since Qlik Sense version September 2017 it seems the color-picker is not working. Probably it has something to do with redesign of color-picker from Qlik side (full color pallete, latest colors in picker ...)

**Comment by mhamano** [comment]
Hi David, thank you for your report. I have noticed the issue in the September 2017 preview, but I have not be able to report the issue yet. I am going to raise the issue to the support to see what I can do to fix it. Thanks.
